name: cadence_mtb
description: A Mountain Bike Guide with Interactive Bike Project, Navigation and Trails in the Philippines.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  animations: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  contacts_service: ^0.6.1
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^10.1.0
  fl_chart: ^0.68.0
  flutter_chips_input: ^2.0.0
  flutter_form_builder: ^9.3.0
  form_builder_extra_fields: ^10.2.0
  form_builder_validators: ^11.0.0
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.0.7
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  google_maps_flutter: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^1.2.2
  intl: ^0.19.0
  material_floating_search_bar: ^0.3.4
  multiavatar: ^0.1.4
  package_info_plus: ^8.0.0
  page_view_indicators: ^2.0.0
  path_provider: ^2.0.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  rive: ^0.13.4
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.0.6
  sliding_up_panel: ^2.0.0+1
  stop_watch_timer: ^3.1.1
  supabase: ^2.2.5
  telephony: ^0.2.0
  url_launcher: ^6.0.6
  wakelock_plus: ^1.2.5
  weather: ^3.1.1
  webview_flutter: ^4.8.0
  youtube_player_flutter: ^9.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.1
  # flutter_lints: ^4.0.0

flutter_native_splash:
    android: true
    web: false
    ios: false
    color: "#FFFFFF"
    color_dark: "#121212"
    image: assets/icons/final_app_icon.png
    image_dark: assets/icons/final_app_icon_dark.png
    android_12:
      color: "#FFFFFF"
      color_dark: "#121212"
      image: assets/icons/final_app_icon.png
      image_dark: assets/icons/final_app_icon_dark.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
  - family: Comfortaa
    fonts:
      - asset: assets/fonts/Comfortaa-Light.ttf
        weight: 300
      - asset: assets/fonts/Comfortaa-Regular.ttf
        weight: 400
      - asset: assets/fonts/Comfortaa-Bold.ttf
        weight: 700
  - family: BillyOhio
    fonts:
      - asset: assets/fonts/BillyOhio.ttf
  - family: LexendGiga
    fonts:
      - asset: assets/fonts/LexendGiga-Regular.ttf

  assets:
    - assets/licenses/
    - assets/animations/
    - assets/icons/
    - assets/icons/home_dashboard/
    - assets/icons/guides_dashboard/
    - assets/images/bike_project/bike_parts/
    - assets/images/bike_project/bike_parts/accessories/bell/
    - assets/images/bike_project/bike_parts/accessories/bottle_cage/
    - assets/images/bike_project/bike_parts/accessories/fender/
    - assets/images/bike_project/bike_parts/accessories/kickstand/
    - assets/images/bike_project/bike_parts/accessories/light/
    - assets/images/bike_project/bike_parts/accessories/phone_holder/
    - assets/images/bike_project/bike_parts/brake_caliper/
    - assets/images/bike_project/bike_parts/casette/7_speed/
    - assets/images/bike_project/bike_parts/casette/8_speed/
    - assets/images/bike_project/bike_parts/casette/9_speed/
    - assets/images/bike_project/bike_parts/casette/10_speed/
    - assets/images/bike_project/bike_parts/crankset/1_speed/
    - assets/images/bike_project/bike_parts/crankset/2_speed/
    - assets/images/bike_project/bike_parts/crankset/3_speed/
    - assets/images/bike_project/bike_parts/frame/full/
    - assets/images/bike_project/bike_parts/frame/hard_trail/
    - assets/images/bike_project/bike_parts/front_deraileur/clamp_on/
    - assets/images/bike_project/bike_parts/front_deraileur/direct_mount/
    - assets/images/bike_project/bike_parts/front_deraileur/e_type/
    - assets/images/bike_project/bike_parts/front_fork/suspension/
    - assets/images/bike_project/bike_parts/handlebar/flat_bar/
    - assets/images/bike_project/bike_parts/handlebar/riser_bar/
    - assets/images/bike_project/bike_parts/pedal/clipless/
    - assets/images/bike_project/bike_parts/pedal/flat/
    - assets/images/bike_project/bike_parts/rear_deraileur/long_cage/
    - assets/images/bike_project/bike_parts/rim/27.5in/
    - assets/images/bike_project/bike_parts/rim/29in/
    - assets/images/bike_project/bike_parts/saddle/cutaway/
    - assets/images/bike_project/bike_parts/saddle/racing/
    - assets/images/bike_project/bike_parts/tire/all_mountain/
    - assets/images/bike_project/bike_parts/tire/cross_country/
    - assets/images/bike_project/bike_parts/tire/trail_riding/
    - assets/images/bike_project/brands/
    - assets/images/first_aid_previews/bleeding/
    - assets/images/first_aid_previews/bruises_and_fractures/
    - assets/images/first_aid_previews/concussion/
    - assets/images/first_aid_previews/cuts_and_scrapes/
    - assets/images/first_aid_previews/dehydration/
    - assets/images/first_aid_previews/insect_bites/
    - assets/images/first_aid_previews/sprain/
    - assets/images/navigate/
    - assets/images/organizations_logo/
    - assets/images/preparation/the_two_essentials/
    - assets/images/preparation/core_gear/
    - assets/images/preparation/core_repair_items/
    - assets/images/preparation/clothing/
    - assets/images/preparation/gear_options/
    - assets/images/preparation/repair_kit_options/
    - assets/images/preparation/freeriding_gear/
    - assets/images/preparation/personal/
    - assets/images/tips_and_benefits_previews/tips/
    - assets/images/tips_and_benefits_previews/benefits/
    - assets/images/trail_previews/agila_base/
    - assets/images/trail_previews/filinvest_mtb_trail/
    - assets/images/trail_previews/fort_bonifacio_army_mtb_trail/
    - assets/images/trail_previews/heroes_bike_trail/
    - assets/images/trail_previews/la_mesa_nature_reserve/
    - assets/images/trail_previews/maarat_basic_trail/
    - assets/images/trail_previews/nuvali_bike_trail/
    - assets/images/trail_previews/tree_house_bike_park/
    - assets/images/trail_previews/wawa_dam/
    - assets/images/trail_previews/yellow_trail/